-- Doing some Exploratory Data Analysis(EDA) to understand the data.
SELECT * FROM category;
SELECT * FROM customers;
SELECT * FROM order_items;
SELECT * FROM inventory;
SELECT * FROM orders;
SELECT * FROM payments;
SELECT * FROM products;
SELECT * FROM sellers;
SELECT * FROM shippings;

SELECT DISTINCT(payment_status)
FROM payments;

SELECT DISTINCT(delivery_status)
FROM shippings;

SELECT * FROM shippings 
WHERE return_date IS NOT NULL;

--6747
SELECT * FROM orders
WHERE order_id=6747

SELECT * FROM payments
WHERE order_id=6747

SELECT * FROM shippings 
WHERE return_date IS  NULL;  --18301 orders are delivered sucessfully without returns




--------------------------------------
-- Business problems
-- advanced Analysis
--------------------------------------


/*
1. Top Selling Products
Query the top 10 products by total sales value.
Challenge: Include product name, total quantity sold, and total sales value.
*/
-- oi-o-pr
-- prod id  
-- sum qty * price per unit
-- group by prod_id
-- top 10 product

SELECT * FROM order_items;
-- creating a new column
ALTER TABLE order_items
ADD COLUMN total_sale FLOAT;

-- UPDATING total_sale value 
UPDATE order_items 
SET total_sale=quantity*price_per_unit

SELECT p.product_id,
       p.product_name,
	   ROUND(SUM(oi.total_sale)::NUMERIC,2) AS total_sale,
	   COUNT(o.order_id) AS total_orders
FROM order_items oi 
JOIN
orders o
ON o.order_id = oi.order_id
JOIN
products p
ON p.product_id=oi.product_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 10;


/*
2. Revenue by Category
Calculate total revenue generated by each product category.
Challenge: Include the percentage contribution of each category to total revenue.
*/
-- c,p.oi
-- group by cate_id,cat_name
-- join cat,pro,ord_item

SELECT 
      c.category_id,
	  c.category_name,
	  ROUND(sum(oi.total_sale)::NUMERIC,2) AS total_sales,
	  ROUND((SUM(oi.total_sale)::NUMERIC / (SELECT SUM(total_sale) FROM order_items)::NUMERIC) * 100, 2) AS contribution_percentage
FROM category c
JOIN
products p
ON c.category_id=p.category_id
JOIN
order_items oi
ON oi.product_id = p.product_id
GROUP BY 1,2
ORDER BY 3 DESC


/*
3. Average Order Value (AOV)
Compute the average order value for each customer.
Challenge: Include only customers with more than 5 orders.
*/
-- C,O,OI
-- JOIN C,O,OI
--GROUP BY C_ID,C_NAME
-- AOV(TOTAL_SALES)
SELECT 
      c.customer_id,
	  CONCAT(c.first_name,' ',c.last_name) AS full_name,
	  --AVG(oi.total_sale),
	  sum(oi.total_sale)/COUNT(o.ORDER_ID) AS AOV,
	  COUNT(o.ORDER_ID) AS total_orders
FROM customers c
JOIN
orders o
ON o.customer_id = c.customer_id
JOIN
order_items oi
ON oi.order_id=o.order_id
GROUP BY 1,2
HAVING COUNT(*)>5;


/*
4. Monthly Sales Trend
Query monthly total sales over the past year.
Challenge: Display the sales trend, grouping by month, return current_month sale, last month sale!
*/
SELECT 
      year,
	  month,
	  total_sale AS current_month_sales,
	  LAG(total_sale,1) OVER() as previous_month_sales
FROM
(SELECT 
      EXTRACT(MONTH FROM o.order_date) AS month,
	  EXTRACT(year FROM o.order_date)as year,
	  ROUND(sum(oi.total_sale)::NUMERIC,2) AS total_sale
FROM orders o
JOIN
order_items oi
ON o.order_id = oi.order_id
WHERE o.order_date>=CURRENT_DATE - INTERVAL '1 YEAR'
GROUP BY 2,1
ORDER BY 2,1 
) AS t1

/*
5. Customers with No Purchases
Find customers who have registered but never placed an order.
Challenge: List customer details and the time since their registration.
*/
--Approach-1
SELECT *
       --CURRENT_DATE-reg_date
FROM customers
WHERE customer_id NOT IN (SELECT
                                DISTINCT customer_id
						  FROM orders);
--Approach-2
SELECT *
FROM customers c
LEFT JOIN 
orders o
ON c.customer_id=o.customer_id
WHERE o.customer_id IS NULL;


/*
6. Least-Selling Categories by State
Identify the least-selling product category for each state.
Challenge: Include the total sales for that category within each state.
*/

WITH ranking AS
(SELECT 
      c.state,
	  cat.category_name,
	  sum(oi.total_sale) as total_sale,
	  DENSE_RANK() OVER(PARTITION BY c.state order by sum(oi.total_sale)) as rank
FROM orders o
JOIN 
customers c
ON o.customer_id = c.customer_id
JOIN
order_items oi
ON oi.order_id = o.order_id
JOIN
products p
ON p.product_id = oi.product_id
JOIN
category cat
ON cat.category_id = p.category_id
GROUP BY 1,2
)

SELECT *
FROM ranking
WHERE rank=1


/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

-- c-o-oi
--c_id group by sum(total_sale)
-- order by total sale
-- rank

SELECT 
      c.customer_id,
	  CONCAT(c.first_name,' ',c.last_name) as name,
	  ROUND(SUM(total_sale)::NUMERIC,2) as total_amount_spent,
	  DENSE_RANK() OVER(ORDER BY SUM(total_sale) DESC) AS rank
FROM customers c
JOIN
orders o
on o.customer_id = c.customer_id
JOIN
order_items oi
ON oi.order_id = o.order_id
GROUP BY 1,2


/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT 
       i.*,
      p.product_name
FROM products p
JOIN
inventory i
ON i.product_id = p.product_id
WHERE i.stock < 10;


/*
9. Shipping Delays
Identify orders where the shipping date is later than 3 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/
select * from shippings s
join orders o on o.order_id=s.order_id

select * from customers

SELECT 
     o.*,
	 s.shipping_providers AS delivery_provider,
	 CONCAT(c.first_name,' ',last_name) as full_name,
	 s.shipping_date - o.order_date AS days_took_to_ship
FROM orders o
JOIN
shippings s
ON o.order_id = s.order_id
JOIN
customers c
ON c.customer_id = o.customer_id
WHERE s.shipping_date - o.order_date >3;


/*
10. Payment Success Rate 
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/
select * from payments;

SELECT 
      p.payment_status,
	  count(*) as total_payments,
	  COUNT(*)/(SELECT COUNT(*) FROM payments)::NUMERIC*100 AS payments_percentage
FROM orders o
JOIN 
payments p
ON o.order_id=p.order_id
GROUP BY 1


/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
select * from sellers;
select * from orders;

WITH top_sellers AS
(SELECT 
      s.seller_id,
	  s.seller_name,
	  SUM(oi.total_sale) as total_sale
FROM sellers s
JOIN
orders o
ON o.seller_id=s.seller_id
JOIN 
order_items oi
ON oi.order_id=o.order_id
GROUP BY 1,2
ORDER BY total_sale DESC
LIMIT 5),

seller_reports
AS 
(SELECT 
     o.seller_id,
	 ts.seller_name,
	 o.order_status,
	 COUNT(*) as total_orders
FROM orders o
JOIN
top_sellers ts
ON o.seller_id=ts.seller_id
WHERE o.order_status NOT IN ('Inprogress','Returned')
GROUP BY 1,2,3
)

SELECT 
      seller_id,
	  seller_name,
	  sum(CASE WHEN order_status='Completed' then total_orders ELSE 0 END) as total_completed_orders,
	  SUM(CASE WHEN order_status='Cancelled' THEN total_orders ELSE 0 END )as total_cancelled_orders,
	  SUM(total_orders) AS total_orders,
	  sum(CASE WHEN order_status='Completed' then total_orders ELSE 0 END)::NUMERIC/
	  SUM(total_orders)::NUMERIC*100 AS sucessful_orders_percentage
FROM seller_reports
Group by 1,2


/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT 
     product_id,
	 product_name,
	 profit_margin,
	 DENSE_RANK() OVER(ORDER BY profit_margin DESC) as product_rank
FROM
(SELECT 
      p.product_id,
	  p.product_name,
	  sum(oi.total_sale-(p.cogs*oi.quantity))/sum(total_sale)*100 as profit_margin
FROM order_items oi
JOIN
products p
ON p.product_id = oi.product_id
GROUP BY 1,2) AS t1


/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/
select * from products
select distinct order_status from orders 

SELECT 
       p.product_id,
	   p.product_name,
	   count(*) as total_units_sold,
	   SUM(CASE WHEN o.order_status='Returned' THEN 1 ELSE 0 END) AS total_returned,
	   SUM(CASE WHEN o.order_status='Returned' THEN 1 ELSE 0 END)::NUMERIC/count(*)*100::NUMERIC AS returned_percentage
FROM order_items oi
JOIN
products p
ON oi.product_id = p.product_id
JOIN
orders o
ON o.order_id = oi.order_id
GROUP BY 1,2
ORDER BY 4 DESC
LIMIT 10;


/*
14. Orders Pending Shipment
Find orders that have been paid but are still pending shipment.
Challenge: Include order details, payment date, and customer information.
*/

SELECT 
      CONCAT(c.first_name,' ',c.last_name) AS full_name,
      o.order_id,
	  o.order_status,
	  p.payment_date,
	  p.payment_status
FROM orders o
JOIN
payments p
ON p.order_id = o.order_id
JOIN
customers c
ON c.customer_id = o.customer_id
WHERE 
p.payment_status='Payment Successed'
AND o.order_status='Inprogress'


/*
15. Inactive Sellers
Identify sellers who haven’t made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/

WITH cte1 -- as these sellers has not done any sale in last 6 month
AS
(SELECT * FROM sellers
WHERE seller_id NOT IN (SELECT seller_id FROM orders WHERE order_date >= CURRENT_DATE - INTERVAL '6 month')
)

SELECT 
      o.seller_id,
      MAX(o.order_date) as last_sale_date,
      MAX(oi.total_sale) as last_sale_amount
FROM orders as o
JOIN 
cte1
ON cte1.seller_id = o.seller_id
JOIN order_items as oi
ON o.order_id = oi.order_id
GROUP BY 1

/*
16. IDENTITY customers into returning or new
if the customer has done more than 5 return categorize them as returning otherwise new
Challenge: List customers id, name, total orders, total returns
*/

SELECT 
      customer_id,
      c_full_name as customers,
      total_orders,
      total_return,
CASE
	WHEN total_return > 5 THEN 'Returning_customers' ELSE 'New'
END as cx_category
FROM
(SELECT 
     c.customer_id,
	 CONCAT(c.first_name, ' ', c.last_name) as c_full_name,
	 COUNT(o.order_id) as total_orders,
	 SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) as total_return	
FROM orders as o
JOIN 
customers as c
ON c.customer_id = o.customer_id
JOIN
order_items as oi
ON oi.order_id = o.order_id
GROUP BY 1,2
)


/*
17. Top 5 Customers by Orders in Each State
Identify the top 5 customers with the highest number of orders for each state.
Challenge: Include the number of orders and total sales for each customer.
*/

SELECT * FROM 
(SELECT 
	c.state,
	CONCAT(c.first_name, ' ', c.last_name) as customers,
	COUNT(o.order_id) as total_orders,
	SUM(total_sale) as total_sale,
	DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(o.order_id) DESC) as rank
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
customers as c
ON 
c.customer_id = o.customer_id
GROUP BY 1, 2
) as t1
WHERE rank <=5


/*
18. Revenue by Shipping Provider
Calculate the total revenue handled by each shipping provider.
Challenge: Include the total number of orders handled and the average delivery time for each provider.
*/

-- oi - o - shipping
-- group by shipping provider id sum(total sale), total orders 

SELECT 
	s.shipping_providers,
	COUNT(o.order_id) as order_handled,
	SUM(oi.total_sale) as total_sale,
	COALESCE(AVG(s.return_date - s.shipping_date), 0) as average_days
FROM orders as o
JOIN 
order_items as oi
ON oi.order_id = o.order_id
JOIN 
shippings as s
ON 
s.order_id = o.order_id
GROUP BY 1

/*
19. Top 10 product with highest decreasing revenue ratio compare to last year(2022) and current_year(2023)
Challenge: Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio at end Round the result

Note: Decrease ratio = cr-ls/ls* 100 (cs = current_year ls=last_year)
*/
WITH last_year_sale AS
(SELECT 
      p.product_id,
	  p.product_name,
	  SUM(oi.total_sale) as revenue
FROM orders o
JOIN
order_items oi
ON o.order_id = oi.order_id
JOIN
products p
ON p.product_id=oi.product_id
WHERE EXTRACT (YEAR FROM o.order_date)=2022
GROUP BY 1,2),

current_year_sale AS
(SELECT 
      p.product_id,
	  p.product_name,
	  SUM(oi.total_sale) as revenue
FROM orders o
JOIN
order_items oi
ON o.order_id = oi.order_id
JOIN
products p
ON p.product_id=oi.product_id
WHERE EXTRACT (YEAR FROM o.order_date)=2023
GROUP BY 1,2)

SELECT 
      ls.product_id,
	  ls.product_name,
	  ls.revenue as last_year_revenue,
	  cs.revenue as current_year_revenue,
	  ls.revenue-cs.revenue AS revenue_diff,
	  ROUND((cs.revenue-ls.revenue)::NUMERIC/ls.revenue::NUMERIC *100,2) AS revenue_decr_ratio
FROM
last_year_sale AS ls
JOIN
current_year_sale AS cs
ON ls.product_id=cs.product_id
WHERE ls.revenue>cs.revenue
ORDER BY 6 DESC


-- STORED PROCEDURE
/*
Final Task
-- Store Procedure
create a function as soon as the product is sold the the same quantity should reduced from inventory table
after adding any sales records it should update the stock in the inventory table based on the product and qty purchased
-- 
*/
SELECT * FROM products
-- product_id 1 -- airpod 3rd gen -- 55stock
-- produ id 2 airpod max --39

SELECT * FROM inventory
WHERE product_id = 1;

SELECT * FROM orders;
SELECT * FROM order_items;
SELECT * FROM inventory;
SELECT * FROM products
order_id,
order_date,
customer_id,
seller_id,
order_item_id,
product_id,
quantity,


CREATE OR REPLACE PROCEDURE add_sales
(
p_order_id INT,
p_customer_id INT,
p_seller_id INT,
p_order_item_id INT,
p_product_id INT,
p_quantity INT
)
LANGUAGE plpgsql
AS $$

DECLARE 
-- all variable
v_count INT;
v_price FLOAT;
v_product VARCHAR(50);

BEGIN
-- Fetching product name and price based p id entered
	SELECT 
		price, product_name
		INTO
		v_price, v_product
	FROM products
	WHERE product_id = p_product_id;
	
-- checking stock and product availability in inventory	
	SELECT 
		COUNT(*) 
		INTO
		v_count
	FROM inventory
	WHERE 
		product_id = p_product_id
		AND 
		stock >= p_quantity;
		
	IF v_count > 0 THEN
	-- add into orders and order_items table
	-- update inventory
		INSERT INTO orders(order_id, order_date, customer_id, seller_id)
		VALUES
		(p_order_id, CURRENT_DATE, p_customer_id, p_seller_id);

		-- adding into order list
		INSERT INTO order_items(order_item_id, order_id, product_id, quantity, price_per_unit, total_sale)
		VALUES
		(p_order_item_id, p_order_id, p_product_id, p_quantity, v_price, v_price*p_quantity);

		--updating inventory
		UPDATE inventory
		SET stock = stock - p_quantity
		WHERE product_id = p_product_id;
		
		RAISE NOTICE 'Thank you product: % sale has been added also inventory stock updates',v_product; 

	ELSE
		RAISE NOTICE 'Thank you for for your info the product: % is not available', v_product;

	END IF;

END;
$$

SELECT COUNT(*) 
FROM inventory
WHERE 
	product_id = 1
	AND 
	stock >= 56


call add_sales
(
25006, 2, 5, 25005, 1, 14
);


(
p_order_id INT,
p_customer_id INT,
p_seller_id INT,
p_order_item_id INT,
p_product_id INT,
p_quantity INT


-- END
































